### ISSUE TITLE
How do i access terminal?

### ISSUE THREAD

**Issue by mizzunet** [HsOjo/LinuxOnAndroid#1]
1. Installed busy ox
2. Extracted ubuntu roofs from AnLinux repo to /.linux
3. Download this repo to /data
4. Ran install.sh
5. Rebooted
6. Now what how do I access Linux?
I tried to run init.sh from the folder, but it had permission issues so I chmod-ed +x on all files,
Then ran again, but it failed
`./exec.sh[5]: /system/xbin/chroot: inaccessible or not found`

It's android 11 btw

**Comment by HsOjo** [comment]
* You should check BusyBox files was existed.
  * (chroot is provided from BusyBox.)
* You can execute open.sh to access linux.
  * (Install ssh in linux is recommend.)

**Comment by mizzunet** [comment]
1. Busybox does exist. And busybox chroot does work.
  There's no /system/xbin folder at all
2. Returns chroot: : No such file or directory

**Comment by mizzunet** [comment]
However, I replaced /system/xbin/chroot with busybox chroot. 
Now it runs, though returns this error
`chroot: can't change root directory to '': No such file or directory`

**Comment by mizzunet** [comment]
It seems like $ROOT variable is null

**Comment by HsOjo** [comment]
> * Busybox does exist. And busybox chroot does work.
>   There's no /system/xbin folder at all
> * Returns chroot: : No such file or directory

Is your BusyBox install from Magisk?

**Comment by mizzunet** [comment]
> > * Busybox does exist. And busybox chroot does work.
> >   There's no /system/xbin folder at all
> > * Returns chroot: : No such file or directory
> 
> Is your BusyBox install from Magisk?

Yes, the one found in the official repo

**Comment by mizzunet** [comment]
Now I got access to the shell. It seems like ROOT hasn't defined here https://github.com/HsOjo/LinuxOnAndroid/blob/master/exec.sh

**Comment by HsOjo** [comment]
> Now I got access to the shell. It seems like ROOT hasn't defined here https://github.com/HsOjo/LinuxOnAndroid/blob/master/exec.sh

* The env.sh should execute on init.sh: line 3, May be some problem in there.
  * (env.sh included $ROOT)
  * But my device can works, Is little strange.
  * https://github.com/HsOjo/LinuxOnAndroid/blob/8692c80/init.sh

**Comment by mizzunet** [comment]
Hm
